const {onCall,onRequest,HttpsError}=require("firebase-functions/v2/https");
const {defineSecret,defineString}=require("firebase-functions/params");
const admin=require("firebase-admin");const crypto=require("crypto");admin.initializeApp();const db=admin.firestore();
const KEY=defineSecret("MIDTRANS_SERVER_KEY"),PROD=defineString("MIDTRANS_PRODUCTION",{default:"false"}),RATE=.10;
const base=()=>PROD.value()==="true"?"https://api.midtrans.com":"https://api.sandbox.midtrans.com";
const auth=()=> "Basic "+Buffer.from(KEY.value()+":").toString("base64");
const uid=r=>{if(!r.auth)throw new HttpsError("unauthenticated","Silakan login.");return r.auth.uid};
const text=(x,n=500)=>String(x??"").trim().slice(0,n);

exports.createStore=onCall(async r=>{let u=uid(r),name=text(r.data?.name,60);if(!name)throw new HttpsError("invalid-argument","Nama toko wajib.");let q=await db.collection("stores").where("ownerId","==",u).limit(1).get();if(!q.empty)return{storeId:q.docs[0].id};let ref=db.collection("stores").doc();await ref.set({ownerId:u,name,description:"",phone:"",address:"",logoUrl:"",bannerUrl:"",rating:0,ratingCount:0,active:true,createdAt:admin.firestore.FieldValue.serverTimestamp()});await db.collection("wallets").doc(u).set({userId:u,availableBalance:0,pendingBalance:0,totalEarned:0,updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});return{storeId:ref.id}});

exports.createOrder=onCall(async r=>{let u=uid(r),items=Array.isArray(r.data?.items)?r.data.items:[],address=text(r.data?.address),phone=text(r.data?.phone,40),payment=text(r.data?.payment,30);if(!items.length)throw new HttpsError("invalid-argument","Keranjang kosong.");if(!address||!phone)throw new HttpsError("invalid-argument","Alamat dan nomor wajib.");if(!["QRIS","BANK_TRANSFER","E_WALLET","COD"].includes(payment))throw new HttpsError("invalid-argument","Metode pembayaran tidak valid.");
let map=new Map();for(let x of items){let id=text(x.productId,100),q=Math.floor(Number(x.qty));if(!id||q<1||q>99)throw new HttpsError("invalid-argument","Item tidak valid.");map.set(id,(map.get(id)||0)+q)}
let snaps=await db.getAll(...[...map.keys()].map(id=>db.collection("products").doc(id)));let lines=[],sub=0,seller=null,store=null,storeName="";
for(let s of snaps){if(!s.exists)throw new HttpsError("not-found","Produk tidak ditemukan.");let p=s.data(),q=map.get(s.id);if(p.active===false||Number(p.stock)<q)throw new HttpsError("failed-precondition","Produk tidak aktif atau stok kurang.");if(!seller){seller=p.sellerId;store=p.storeId;storeName=p.storeName||""}if(p.sellerId!==seller)throw new HttpsError("failed-precondition","Checkout harus satu toko.");let price=Math.round(Number(p.price));sub+=price*q;lines.push({productId:s.id,name:text(p.name,200),price,qty:q,imageUrl:p.imageUrl||"",sellerId:p.sellerId,storeId:p.storeId})}
let fee=Math.round(sub*RATE),rev=sub-fee,ref=db.collection("orders").doc();await db.runTransaction(async tx=>{for(let l of lines){let pr=db.collection("products").doc(l.productId),s=await tx.get(pr);if(Number(s.data().stock)<l.qty)throw new HttpsError("failed-precondition","Stok berubah.");tx.update(pr,{stock:Number(s.data().stock)-l.qty,updatedAt:admin.firestore.FieldValue.serverTimestamp()})}tx.set(ref,{buyerId:u,sellerId:seller,storeId:store,storeName,address,phone,payment,subtotal:sub,shipping:0,total:sub,platformFee:fee,sellerRevenue:rev,status:payment==="COD"?"pending":"waiting_payment",paymentStatus:payment==="COD"?"cod":"pending",balanceReleased:false,createdAt:admin.firestore.FieldValue.serverTimestamp(),updatedAt:admin.firestore.FieldValue.serverTimestamp()});for(let l of lines)tx.set(ref.collection("items").doc(),l)});return{orderId:ref.id,total:sub}});

exports.createPayment=onCall({secrets:[KEY]},async r=>{let u=uid(r),id=text(r.data?.orderId,100),ref=db.collection("orders").doc(id),s=await ref.get();if(!s.exists)throw new HttpsError("not-found","Order tidak ditemukan.");let o=s.data();if(o.buyerId!==u)throw new HttpsError("permission-denied","Bukan pesanan Anda.");if(o.payment==="COD"||o.paymentStatus==="paid")throw new HttpsError("failed-precondition","Pembayaran tidak diperlukan.");let old=await db.collection("payments").doc(id).get();if(old.exists&&old.data().status==="pending")return old.data();
let body=o.payment==="QRIS"?{payment_type:"qris",transaction_details:{order_id:id,gross_amount:Number(o.total)},qris:{acquirer:"gopay"}}:o.payment==="BANK_TRANSFER"?{payment_type:"bank_transfer",transaction_details:{order_id:id,gross_amount:Number(o.total)},bank_transfer:{bank:"bca"}}:{payment_type:"gopay",transaction_details:{order_id:id,gross_amount:Number(o.total)},gopay:{enable_callback:true}};
let rr=await fetch(base()+"/v2/charge",{method:"POST",headers:{"Content-Type":"application/json",Authorization:auth()},body:JSON.stringify(body)}),d=await rr.json();if(!rr.ok)throw new HttpsError("internal",d.status_message||"Midtrans error");
let out={orderId:id,amount:Number(o.total),status:"pending",transactionId:d.transaction_id||"",paymentType:o.payment,createdAt:admin.firestore.FieldValue.serverTimestamp(),updatedAt:admin.firestore.FieldValue.serverTimestamp()};let qr=d.actions?.find(x=>x.name==="generate-qr-code"),deep=d.actions?.find(x=>x.name==="deeplink-redirect");if(qr)out.qrUrl=qr.url;if(deep)out.deeplink=deep.url;if(d.va_numbers?.[0]){out.bank=d.va_numbers[0].bank;out.vaNumber=d.va_numbers[0].va_number}await db.collection("payments").doc(id).set(out);return out});

exports.midtransWebhook=onRequest({secrets:[KEY]},async(req,res)=>{if(req.method!=="POST")return res.status(405).send("Method Not Allowed");try{let{order_id,status_code,gross_amount,signature_key,transaction_status,fraud_status}=req.body||{};let sig=crypto.createHash("sha512").update(order_id+status_code+gross_amount+KEY.value()).digest("hex");if(sig!==signature_key)return res.status(401).send("Invalid signature");let or=db.collection("orders").doc(order_id),pr=db.collection("payments").doc(order_id);await db.runTransaction(async tx=>{let os=await tx.get(or);if(!os.exists)throw Error("Order missing");let o=os.data();if(String(o.total)!==String(gross_amount))throw Error("Amount mismatch");let paid=transaction_status==="settlement"||(transaction_status==="capture"&&fraud_status==="accept");let failed=["cancel","deny","expire"].includes(transaction_status);if(paid){if(o.paymentStatus==="paid")return;let wr=db.collection("wallets").doc(o.sellerId),ws=await tx.get(wr),w=ws.exists?ws.data():{},lr=db.collection("walletLedger").doc(order_id),ls=await tx.get(lr);if(!ls.exists){tx.set(lr,{orderId:order_id,sellerId:o.sellerId,type:"sale",amount:o.sellerRevenue,createdAt:admin.firestore.FieldValue.serverTimestamp()});tx.set(wr,{userId:o.sellerId,pendingBalance:Number(w.pendingBalance||0)+Number(o.sellerRevenue),availableBalance:Number(w.availableBalance||0),totalEarned:Number(w.totalEarned||0)+Number(o.sellerRevenue),updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true})}tx.update(or,{paymentStatus:"paid",status:"processing",updatedAt:admin.firestore.FieldValue.serverTimestamp()});tx.set(pr,{status:"paid",transactionStatus,updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true})}else if(failed){tx.update(or,{paymentStatus:transaction_status,status:"payment_failed",updatedAt:admin.firestore.FieldValue.serverTimestamp()});tx.set(pr,{status:transaction_status,updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true})}else tx.set(pr,{status:"pending",transactionStatus,updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true})});res.status(200).send("OK")}catch(e){console.error(e);res.status(500).send("Webhook error")}});

exports.confirmDelivery=onCall(async r=>{let u=uid(r),id=text(r.data?.orderId,100),ref=db.collection("orders").doc(id);await db.runTransaction(async tx=>{let s=await tx.get(ref);if(!s.exists)throw new HttpsError("not-found","Order tidak ditemukan.");let o=s.data();if(o.buyerId!==u)throw new HttpsError("permission-denied","Bukan pesanan Anda.");if(o.status==="delivered")return;if(o.status!=="shipped")throw new HttpsError("failed-precondition","Belum dikirim.");let wr=db.collection("wallets").doc(o.sellerId),ws=await tx.get(wr),w=ws.exists?ws.data():{},lr=db.collection("walletLedger").doc(id+"_release"),ls=await tx.get(lr);if(!ls.exists){tx.set(lr,{orderId:id,sellerId:o.sellerId,type:"release",amount:o.sellerRevenue,createdAt:admin.firestore.FieldValue.serverTimestamp()});tx.set(wr,{pendingBalance:Math.max(0,Number(w.pendingBalance||0)-Number(o.sellerRevenue)),availableBalance:Number(w.availableBalance||0)+Number(o.sellerRevenue),updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true})}tx.update(ref,{status:"delivered",balanceReleased:true,deliveredAt:admin.firestore.FieldValue.serverTimestamp(),updatedAt:admin.firestore.FieldValue.serverTimestamp()})});return{ok:true}});

exports.requestPayout=onCall(async r=>{let u=uid(r),amount=Math.round(Number(r.data?.amount)),bank=text(r.data?.bank,50),accountNumber=text(r.data?.accountNumber,50),accountHolder=text(r.data?.accountHolder,100);if(amount<10000||!bank||!accountNumber||!accountHolder)throw new HttpsError("invalid-argument","Data payout tidak lengkap.");let wr=db.collection("wallets").doc(u),pr=db.collection("payouts").doc();await db.runTransaction(async tx=>{let s=await tx.get(wr),w=s.exists?s.data():{};if(Number(w.availableBalance||0)<amount)throw new HttpsError("failed-precondition","Saldo tidak cukup.");tx.update(wr,{availableBalance:Number(w.availableBalance||0)-amount,updatedAt:admin.firestore.FieldValue.serverTimestamp()});tx.set(pr,{sellerId:u,amount,bank,accountNumber,accountHolder,status:"pending",createdAt:admin.firestore.FieldValue.serverTimestamp()})});return{payoutId:pr.id}});

exports.createReview=onCall(async r=>{let u=uid(r),id=text(r.data?.orderId,100),rating=Math.round(Number(r.data?.rating));if(rating<1||rating>5)throw new HttpsError("invalid-argument","Rating 1-5.");let ref=db.collection("reviews").doc(id+"_"+u),or=db.collection("orders").doc(id);await db.runTransaction(async tx=>{let s=await tx.get(or);if(!s.exists)throw new HttpsError("not-found","Order tidak ditemukan.");let o=s.data();if(o.buyerId!==u||o.status!=="delivered")throw new HttpsError("permission-denied","Ulasan belum diizinkan.");let old=await tx.get(ref);if(old.exists)throw new HttpsError("already-exists","Sudah diulas.");tx.set(ref,{orderId:id,buyerId:u,sellerId:o.sellerId,storeId:o.storeId,rating,comment:text(r.data?.comment,1000),createdAt:admin.firestore.FieldValue.serverTimestamp()})});return{ok:true}});
